### ISSUE TITLE
Why are we capturing SIGINT ?

### ISSUE THREAD

**Issue by MaG21** [atipugin/telegram-bot-ruby#151]
https://github.com/atipugin/telegram-bot-ruby/blob/729a05dc066f2d667ea87a8d218bda37db9ef591/lib/telegram/bot/client.rb#L24

```ruby
      def listen(&block)
        logger.info('Starting bot')
        running = true
        Signal.trap('INT') { running = false }
        fetch_updates(&block) while running
        exit
      end
```

I think it would be better if the logic of capturing signals it's left to the developer at a higher level, so he or she uses the approach they consider best.

Proposition. ( throw/catch )

```ruby
def listen(&block)
     catch(:stop) {
          loop { fetch_updates(&block) }
     }
     exit   # <- why?
end

def stop
     throw :stop
end
```

Now the developer has the option to stop the bot in any way they want.

```ruby
bot.stop
# or
trap("SIGTERM") { $bot.stop }
```

**Comment by Coolomina** [comment]
Agree. 

I don't know if related, but it's a bit annoying when I want to stop my dev server with CTRL + C and I have to wait for the library to complete some hidden process (fetch_updates, probably). It takes about 15 seconds to finish since the SIGINT, so I end up sending a SIGTERM via terminal.

Is this the expected behavior?

**Comment by atipugin** [comment]
@MaG21 `#listen` method is just for convenience and can be easily replaced by your own loop with custom logic, signal handling etc. What's why `#fetch_updates` method was extracted (https://github.com/atipugin/telegram-bot-ruby/commit/dea1617d7d09b009fba875373fba4ac74c082202) and can be accessed directly.

@Coolomina Yes, it's expected behavior.

**Comment by MaG21** [comment]
@atipugin still, people  will benefit more if `#listen` has more sensible defaults.
