### ISSUE TITLE
Stop using `inflecto` dependency

### ISSUE THREAD

**Issue by mbj** [atipugin/telegram-bot-ruby#235]
Inflecto is *unmaintained*. And I'm thinking about nuking it from the `rubygems.org`. Better move to better maintained alternatives: https://github.com/mbj/inflecto#discontinued

**Comment by mbj** [comment]
Thoughts on why I consider to yank it: https://twitter.com/_m_b_j_/status/1401845129137250306

**Comment by atipugin** [comment]
Hi @mbj 

First of all, thx for your work! Unfortunately it's not that simple, because this gem still relies on virtus, which in turn [relies on inflecto](https://github.com/solnic/virtus/blob/a6f8969841247462bb05c456458baa66fce29ed8/lib/virtus/attribute/builder.rb#L30). Maybe it's a good time to rewrite gem using dry-types.

**Comment by mbj** [comment]
> Maybe it's a good time to rewrite gem using dry-types.

likely. Or stop using inflection / implicit coercions.

BTW: virtus has no hard dependency AFAIK, but it could be the reason I still see so many downloads of `inflecto` (I want to stop). I was not aware it ever used inflecto.

**Comment by mbj** [comment]
> First of all, thx for your work! 

Same, cheers.

**Comment by atipugin** [comment]
@mbj i've released 0.16 with virtus v2 and w/o inflecto 🎉
