### ISSUE TITLE
how to substitute the https://api.telegram.org end-point with proxy?

### ISSUE THREAD

**Issue by timfong888** [atipugin/telegram-bot-ruby#63]
Some clients for other end-points allow me to change the end-point being called with a proxy so that I can instrument each call to the API.

I looked at the `conn` method but it's private so I cannot access it.

Thoughts?

**Comment by atipugin** [comment]
Unfortunately, there is no way to do it for now.

**Comment by aspotashev** [comment]
You can monkey patch like this:

`--- /dev/null
+++ b/config/initializers/replace_telegram_api_url.rb
@@ -0,0 +1,16 @@
+module Telegram
+  module Bot
+    class Api
+      def conn
+        url = ENV['TELEGRAM_BOT_API_URL']
+        url ||= 'https://api.telegram.org'
+
+        @conn ||= Faraday.new(url: url) do |faraday|
+          faraday.request :multipart
+          faraday.request :url_encoded
+          faraday.adapter Telegram::Bot.configuration.adapter
+        end
+      end
+    end
+  end
+end
`

**Comment by timfong888** [comment]
Could we create a pull request to enable the above but as a config to the method?

**Comment by fetsh** [comment]
Now we need this!

**Comment by atipugin** [comment]
Looks like time has come :(

**Comment by aspotashev** [comment]
Hey guys,

I don't get how changing the server URL could help fight censorship in Russia. Or are you trying to use an SSH tunnel as a proxy?

For me, replacing real Telegram server (at api.telegram.org) with a mock (at localhost) was necessary in order to run integration tests against the full stack of my Telegram bot.

If you are connecting to a real Telegram but suffer from regional censorship, you can overcome it by
 1. Using VPN or
 2. Using another type of proxy, e.g. SOCKS5. However Faraday does not support SOCKS5 out of the box. So the easiest way is going to be VPN.

**Comment by lenferer** [comment]
Hey guys,
This `https://github.com/atipugin/telegram-bot-ruby/pull/180` resolve problem with proxy.
